### ISSUE TITLE
--split_fasta

### ISSUE THREAD

**Issue by tillenglert** [ncbi/fcs#19]
Hi,

I just wanted to ask if there is a documentation on the parameter split_fasta or if you can maybe tell, what exactly it does?

Thank you in advance,

Till

**Comment by pstrope** [comment]
```
$ singularity exec fcs-gx.0.2.3.sif gx  --help
SYNOPSIS
    gx split-fasta [-i <input=stdin>] [-o <output=stdout>]

OPTIONS
    split-fasta     command: Split fasta from stdin on N-runs of length at least 10. --input is fasta.

$ singularity exec  --bind $PWD:/host fcs-gx.0.2.3.sif  gx split-fasta --input=/host/test.fa
```

**Comment by tillenglert** [comment]
Hi thank you for you answer,

so this option/tool will split the given fasta into N-chunks for internal analysis? Is there an option to set N? I want to include the tool into a pipeline and for testing I want to produce reproducible results. So if I understand the split-fasta correctly I could analyse the fasta in one chunk to reduce variability?

**Comment by tillenglert** [comment]
Hi thank you for your answer,

so this option splits the fasta file into N-Chunks for internal analysis or did I get this wrong? Will it change the reproducibility for larger analysis? I couldn't see a difference for the test-only dataset.

**Comment by pstrope** [comment]
Hi,
It splits the input fasta wherever there are 10 or more N's. If you look at [the taxonomy report](https://github.com/ncbi/fcs/wiki/FCS-GX-taxonomy-report), it shows how split sequences are given seq-id's based on their split ranges. It will not change the reproducibility for the same version of the software.

There was a bug, that this parameter was set to default:True in this version, that's why you didn't see the difference.  In our next release we will have the option to set this on and off. 

Thank you for your feedback. It really helps us.

**Comment by tillenglert** [comment]
Hi,

thanks for clearing that up, I was confused by the N-runs!
