### ISSUE TITLE
Understanding output

### ISSUE THREAD

**Issue by RNieuwenhuis** [ncbi/fcs#45]
Hi,

I ran fcs-gx on a HiFi assembly of a large plant genome. The output of the log is shown below. 

```

Collecting masking statistics...
Collected masking stats:  38.8906 Gbp; 486.992s; 79.8588 Mbp/s. Baseline: 7.04942

Processed 59335 queries, 38925Mbp in 1212.43s. (32.105Mbp/s); num-jobs:388889
Asserted div               : plnt:plants
Inferred primary-divs      : ['plnt:plants']
Corrected primary-divs     : ['plnt:plants']
Putative contaminant divs  : ['prok:g-proteobacteria', 'prok:b-proteobacteria']
Aggregate coverage         : 0%
Minimum contam. coverage   : 60%

--------------------------------------------------------------------

fcs_gx_report.txt contamination summary:
----------------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                             49   14436711
-----                          ----- ----------
prok:g-proteobacteria             47    7453082
prok:b-proteobacteria              2    6983629

--------------------------------------------------------------------

fcs_gx_report.txt action summary:
---------------------------------
                                seqs      bases
                               ----- ----------
TOTAL                             49   14436711
-----                          ----- ----------
EXCLUDE                           49   14436711

--------------------------------------------------------------------

```

I find that in the `.rpt` file all of my contigs *not listed as contaminants* are shown as `repeat` and the column `reserved` shows only `n/a`. I find it hard to understand records like the one pasted below. A large part is masked (as expected for such a big plant genome) but the part that is not returns hits to non-plant taxa. Does this make sense? What is the effect of masking on the final classification? 

```
ptg012753l	238703	226397,3601,100,0	1225	|	Penaeus japonicus	27405	anml:crustaceans	436	436	41	|	218467	anml:insects	557	295	21	|	7604	anml:echinoderms	202	202	16	|	45264	anml:basal metazoans	215	215	15	|	n/a	repeat	anml:crustaceans	0
```

**Comment by etvedte** [comment]
Hello,

The example sequence that you provided is treated as a valid sequence belonging to your plant genome. It won't end up in the GX action report and will still be in your final FASTA following a cleaning step.

The first number in the column 3 tuple `226397` corresponds to a transposons repeats track that GX reports as part of repeats detection/masking. The sequence length in this track is 95% of the total contig length, which is above a reporting threshold for assigning this sequence as a 'repeat'. The off-target hits to animals are likely spurious, but since they are so small in comparison to the large tracts of repeats, there are no contamination calls. The `reserved` column is an unused column from a previous GX version and can be ignored.

This appears to be a novel plant genome with respect to the plant genomes in our reference database. The `Aggregate coverage : 0%` metric means that there is overall very small overlap between query and reference sequences. This also means is that the GX contamination coverage requirement is higher to confidently call a sequence a contaminant `Minimum contam. coverage : 60%` such that the sequences assigned prokaryote contaminants likely have high coverage in the taxonomy/action report files.

Eric
