### ISSUE TITLE
non-containerized version?

### ISSUE THREAD

**Issue by nextgenusfs** [ncbi/fcs#5]
Is the backend code available? Requiring docker or singularity to run this negatively impacts using it in pipelines, etc.

**Comment by d4straub** [comment]
Not a maintainer here, just wanted to use the tool and had the idea of using https://github.com/ncbi/fcs/blob/main/dist/run_fcsadaptor.sh#L111-L113 in the container instead of run_fcsadaptor.sh itself (avoiding container-in-container situations). But the container doesnt contain bash, so not usable (yet?) when attempting to use it in a nextflow pipeline (in case relevant, see https://github.com/ncbi/fcs/issues/4).

**Comment by deaconjs** [comment]
Thanks for your interest in our source code! We have been planning to release the FCS-GX and FCS-adaptor source this fall as we prepare a publication. To address your request we will discuss logistics for earlier release. We are continuing to make improvements, so it will be important for early users in particular to maintain the latest changes for their own pipelines.

The FCS-adaptor code utilizes the NCBI C++ Toolkit, and is more complicated to build from source. Would you like the option to download pre-built binaries from FTP?

**Comment by nextgenusfs** [comment]
Download the binaries would be fine, I assume similar to `tbl2asn`, etc?

**Comment by deaconjs** [comment]
We see on the funannotate issue #759 that you've decided to work with your own vecscreen contig cleaner for this. Are there ways the current adaptor docker image is not meeting your expectations? We intend to release the adaptor screen CWL and embedded tools, but a GX publication is our current top priority so it not happen for a few months.

**Comment by etvedte** [comment]
Closing. Please follow-up if you have other questions.
