### ISSUE TITLE
Fatal error trying to clean genome using fcs.py

### ISSUE THREAD

**Issue by hugh0335** [ncbi/fcs#66]
Hello,   

We are workgin to submit a genome and were instructed to run fcs adaptor tool.  W are now attempting to mask internal adaptors instead of split at these sites.  

Started by following github code to run run_fcsadaptor.sh on a fasta.  Outputted the fcs_adaptor_report.txt and modified so "ACTION_TRIM" become "FIX" as decsribed here: https://github.com/ncbi/fcs/wiki/FCS-adaptor 

I am now attempting to remove contaminated sequences using the edited fcs_adaptor_report.txt and encountering a fatal flaw on a certain contig.  

`cat ./input.fasta | python3 ./fcs.py clean genome --action-report fcs_adaptor_report_mask.txt --output clean.fasta --contam-fasta-out contam.fasta`

Error received states:
'While loading row 7 of the action report:
contig_10268	12751	FIX	12715..12751	CONTAMINATION_SOURCE_TYPE_ADAPTOR:NGB01107.1:Oxford Nanopore Technologies Ligation Sequencing Kit (SQK-LSK114) Ligation Adaptor Y Top polyT masked	
Fatal error: fasta.cpp:593 in ApplyActionReport(...): Assertion failed: action != "FIX" || ((ivl.pos != 1) && (stop_pos != seq_len))'

Thanks for any guidance.

**Comment by hugh0335** [comment]
[fcs_adaptor_report_mask.txt](https://github.com/ncbi/fcs/files/14028820/fcs_adaptor_report_mask.txt)

**Comment by etvedte** [comment]
Hello,

I replicated this error message with a test sequence set.

The first six sequences in your attached adaptor_report file are true internal sequences. Starting with `contig_10268` and continuing throughout what appears to be the remainder of the contigs, the adaptors are at sequence ends. The error message occurs because you are setting the FIX boundary at the edge of a contig. 

I think if you convert all calls at contig ends to "TRIM" it should work. This is also our preferred behavior for genome submissions, i.e. remove contamination at contig ends.

Thank you for finding this, it will help improve our documentation. Let me know if you run into additional issues.

Eric

**Comment by hugh0335** [comment]
Ok I went back into the file and changed the contigs to TRIM and processed it.  However it does not look like it effectively masked the internal adaptors 

`cat ./cleaned_sequences/scaff_cleaned.fasta | python3 ./fcs.py clean genome --action-report fcs_adaptor_report_mask2.txt --output clean_masked.fasta --contam-fasta-out contam_masked.fasta
Applied 0 actions; 0 bps dropped; 0 bps hardmasked.`

**Comment by etvedte** [comment]
Did you set to `TRIM` or `ACTION_TRIM`? With `fcs.py` only `TRIM` is working to drop contig ends in my test.

**Comment by etvedte** [comment]
Closing. Please reopen if you need to discuss further.
