### ISSUE TITLE
Can FCS-GX be used to batch process a large number of genomes with different taxid?

### ISSUE THREAD

**Issue by ShenMJ99** [ncbi/fcs#93]
I am using `run_gx` compiled from GitHub source code and `gx` from Bioconda. I would like to know if the current version of fcs-gx has any parameters or features that enable batch processing of genomes with different tax-id?

**Comment by etvedte** [comment]
From source code, you should be able to set an environment variable for GX to run on a set number of cores (default=48):
`export GX_NUM_CORES=N` 

Then, you can set up a batch job using xargs or your preferred method. The example below is for running three cases.

```
cat gx_args
run_gx.py --tax-id=562 --fasta=Ecoli.fasta --out-dir=/path/to/outdir --gx-db=/path/to/gxdb/all 
run_gx.py --tax-id=9606 --fasta=Hsapiens.fasta --out-dir=/path/to/outdir --gx-db=/path/to/gxdb/all 
run_gx.py --tax-id=7227 --fasta=Dmel.fasta --out-dir=/path/to/outdir --gx-db=/path/to/gxdb/all 

xargs -a gx_args -L1 -I v1 -P 3  sh -c "v1"
```
FYI we haven't done performance testing for a while, so you'll have to see what works best for your situation. When doing batch jobs, I typically reserve at least 24 cores for larger eukaryote genomes, but you may be able to go lower.

**Comment by ShenMJ99** [comment]
OK, thanks!

**Comment by ckeeling** [comment]
Hello @etvedte 

If not using a tmpfs- or ramfs-backed filesystem, would your suggestion above require that the database be loaded into RAM with each run_gx.py command? In my case, it is taking more than 3 hours to do this initial step of loading into RAM (and thus wasting resources of the high memory node it later needs to be processed within a shared, SLURM-managed, environment). An option to use an input file containing assembly file paths and taxids that the program can internally loop through would probably be a welcome enhancement.

Also, curious, I don't see any reference to run_gx.py in the Code, only in Issues. Has this changed to just using fcs.py?

Thanks!

**Comment by etvedte** [comment]
Hi @ckeeling ,

> I don't see any reference to run_gx.py in the Code, only in Issues.

`run_gx.py` is a script used to perform FCS-GX executables when the code is compiled from [source code](https://github.com/ncbi/fcs-gx), `fcs.py` runs FCS-GX commands using Docker/Singularity containers. We recommend the containerized execution when possible.

> If not using a tmpfs- or ramfs-backed filesystem, would your suggestion above require that the database be loaded into RAM with each run_gx.py command?

This [issue](https://github.com/ncbi/fcs-gx/issues/4) may be of some help. For your specific use case, I would recommend limiting to one process (looping through one genome at a time), otherwise the gxdb build may be wonky. If you loop through genomes the executions should be quick enough to access the cached db files before they are removed.

I can make a note of the suggestion to use a manifest file containing assembly paths/taxids as input, but I would say that this type of solution wouldn't be implemented anytime soon given the competing priorities of the dev team and the existence of alternative solutions to pass through multiple files.
